### ISSUE TITLE
red/black vs blue/green

### ISSUE THREAD

**Issue by deadlysyn** [spinnaker/spinnaker.github.io#1056]
Hi folks,

Enjoying reading about spinnaker!  Awesome project...  Going over this:

https://www.spinnaker.io/concepts

I see the last sentence:

"Spinnaker supports the red/black (a.k.a. blue/green) strategy, with rolling red/black and canary strategies in active development."

I've noticed Netflix always tends to use "red/black", so maybe this is just loyalty to company colors.  :-)  Historically, red/black and blue/green did have a slight but significant distinction.  The (apparently unpopular) answer (the second one from Paulo) in this SO thread gives an accurate summary based on my historic recollection and popular reference texts like the _Continuous*_ series:

https://stackoverflow.com/questions/45259589/whats-the-difference-between-red-black-deployment-and-blue-green-deployment

Since our industry is rife with acronyms and terms, overloading them, inventing new for the sake of inventing, etc just raises the barrier to entry for new community members.

So we had red/black and blue/green with specific meaning, but the spinnaker docs conflate the two...then seem to invent "rolling red/black" to represent what blue/green means.  Finally, the diagrams all talking about red/black are conveniently labeled in blue/green.  :-)

There may be an opportunity for "community UX improvement" to help reduce new terms and be as accurate as possible in ones we must use (reduce cognitive load).

$0.0000000001 (with inflation)

**Comment by dorbin** [comment]
@deadlysyn 
Thanks for your comment. There's definitely is some dissonance in this terminology. 

Two points:
* For Spinnaker purposes red/black and blue/green are synonymous.
* It would be great to standardize on one or the other, but it turns out not to be a simple matter of changing which we use on spinnaker.io. The terms appear in the UI and in the code; making this change is not trivial. You're welcome to submit PRs in spinnaker/spinnaker and spinnaker/spinnaker.github.io if you can solve this.

Thanks!
