### ISSUE TITLE
how to skip SSL validation, while taking to a secure Jenkins Server. 

### ISSUE THREAD

**Issue by eldo26** [spinnaker/spinnaker.github.io#1764]
Page: [/setup/ci/jenkins/](https://www.spinnaker.io/setup/ci/jenkins/)

Feedback:

**Comment by plumpy** [comment]
Thanks for filing this issue. It looks like this might be a request for help rather than a bug. In that case, you're probably better off looking for answers [from our Slack community](https://join.spinnaker.io/), since there is a larger pool of users there. Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel.
