### ISSUE TITLE
Hi, I can see that Cloud Foundry is not mentionned as Supported Provider even if the github project has the code for this support. Why? Thanks

### ISSUE THREAD

**Issue by Imosthep** [spinnaker/spinnaker.github.io#236]
Page: /setup/providers/

Feedback:

**Comment by skim1420** [comment]
Cloud Foundry is no longer an active component, and therefore not supported, due to there being no one being dedicated to the task.

We haven't truncated the codebase yet, but you'll notice that all our recommended mechanisms for instantiating and managing Spinnaker (e.g. halyard) do not include Cloud Foundry.
