### ISSUE TITLE
Some mistake in expression docs

### ISSUE THREAD

**Issue by yue9944882** [spinnaker/spinnaker.github.io#310]
Page: /guides/user/pipeline-expressions/

Feedback:

In the document, it's used as a java example that:

${ new java.text.SimpleDateFormat('mm-dd-yyyy').format(new java.util.Date()) }

Actually it should be ${ new java.text.SimpleDateFormat('MM-dd-yyyy').format(new java.util.Date()) }, cuz upper case 'M' denotes MONTH, but 'm' denotes MINUTE.

**Comment by duftler** [comment]
Thanks.

**Comment by stsully** [comment]
Hate to bring up old stuff... but the expression in the published doc is wrong. It shows:
`${ new java.text.SimpleDateFormat('MM-DD-YYYY').format(new java.util.Date()) }`
This will unfortunately give me the _day of year_ for DD instead of day of month.
it should probably read:
`${ new java.text.SimpleDateFormat('MM-dd-yyyy').format(new java.util.Date()) }`
