### ISSUE TITLE
Update Halyard GKE quickstart, per spinnaker/spinnaker #1891

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#711]
https://github.com/spinnaker/spinnaker/issues/1891#issuecomment-348185794

**Comment by dorbin** [comment]
@nhayes  see also https://spinnakerteam.slack.com/archives/C091CCWRJ/p1525097808000718

**Comment by dorbin** [comment]
@ttomsu fyi

**Comment by ttomsu** [comment]
@dorbin - You probably don't want directly to a slack message, because there is only a 10k limit on message history. We slam through that limit, so the knowledge/bug report is lost to the ether.

Here's the full text:

> Tobi [9:39 AM]
Hello, I am trying to set up spinnaker on Google Container Engine. This guide seems outdated: https://www.spinnaker.io/setup/quickstart/halyard-gke/ - it does not use RBAC and therefore fails `! ERROR Unable to communicate with your Kubernetes cluster: Failure executing: GET at: https://xx.xx.xx.xx/api/v1/namespaces. Message: Forbidden!`
The Google Guide using Helm does not show how to add my own cluster and pushes just its own json definition of a pipeline, leaving me without being able to create my own pipeline on the cluster (dropdowns are empty) 
https://cloud.google.com/solutions/continuous-delivery-spinnaker-kubernetes-engine
> Can someone point me towards and up2date blogpost or guide for GKE and Spinnaker?


> Tobi [9:58 AM]
Solved it: `@dchw Your trick solved my issue.`https://github.com/spinnaker/spinnaker/issues/2421 (edited)

**Comment by avh121** [comment]
Re: #1891, looks like there are already instructions at the beginning of the codelab to enable the Cloud Resource Manager API ([here](https://www.spinnaker.io/setup/quickstart/halyard-gke/#enable-apis)). It might be worth adding a note later on that if repos aren't showing up in your docker registry you should check the Resource Manager API (open to opinions on whether that's worthwhile?), but otherwise I think this issue is already resolved.

**Comment by dorbin** [comment]
Yeah, you're right. As far as that codelab goes and as far as that issue goes (enabling that api), we're good. 

And I just looked in the solution that was also referenced in that issue, and it also includes the instruction to enable the Resource Manager API. 

@viglesiasce and @lwander , is there anything else raised in [#1891](https://github.com/spinnaker/spinnaker/issues/1891) missing in the docs?

**Comment by viglesiasce** [comment]
Could we log something more indicative when we see this error?

**Comment by lwander** [comment]
Hard to say if it's a 403, and if we don't have permission to check API status (or recommended roles don't AFAIK) there's not much to guess at.

**Comment by viglesiasce** [comment]
You could list the things to check. This is obviously an area where users have struggled I think we can do better.
