### ISSUE TITLE
Zero-to-1: Install Halyard through configure K8sV1

### ISSUE THREAD

**Issue by dorbin** [spinnaker/spinnaker.github.io#819]
Solve how to make Hal install clearer, plus the transition to install Choose Provider, and make sure K8sV1 provider instructions are bullet proof, b/c that's currently the canonical env for running Spinnaker.

**Comment by justinwhite** [comment]
At minimum [step 1](https://www.spinnaker.io/setup/install/halyard/) should mention something about k8s. It's a bit unsettling arriving at [step 3](https://www.spinnaker.io/setup/install/environment/) thinking you're en route to a proper installation only to find out a rather large requirement (k8s) has been omitted up until now. I guess there is some responsibility on the reader to understand the entire process before starting, but I think the spirit of this issue is to make things easier for the target audience - right?

**Comment by dorbin** [comment]
Very good point, @justinwhite . I'll probably add this to the overview rather than to step 1, but yes it needs to be mentioned up front. I'm doing a deep analysis of the entire process now, and there I'm finding other pitfalls that probably deserve to be mentioned at the start. Stay tuned.

**Comment by dorbin** [comment]
#844
