### ISSUE TITLE
Jenkins CI setup guide contains unclear references to Igor and Orca

### ISSUE THREAD

**Issue by tillig** [spinnaker/spinnaker.github.io#922]
The section in the setup guide [pertaining to Jenkins integration](https://www.spinnaker.io/setup/ci/jenkins/) ([source](https://github.com/spinnaker/spinnaker.github.io/blob/master/setup/ci/jenkins.md)) there is a section "Configuring Spinnaker" that references Igor and Orca. For example, "Enable Igor" is all the direction you get with reference to Igor.

If you're following along the setup guide, Igor isn't enabled by default and there is no other reference anywhere explaining how to do this. Looking in the default `.hal/` folder, there's no `igor.yml` anywhere in there, so the [Igor README](https://github.com/spinnaker/igor/blob/master/README.md) also doesn't provide any clarification.

The Orca reference tells me to restart Orca. What does that mean in a Kubernetes deployment? Just kill the pod?

I found my Igor answer [by digging through forums](https://community.spinnaker.io/t/spinnaker-and-jenkins-debug/314), but based on that thread it appears I'm not the only one confused. That, and I'm not entirely sure I did it right. Does it really require manual YAML hacking or is there a Halyard command I'm missing?

It would be good to add some clarification on how to enable Igor and restart Orca such that folks following along the setup guide aren't left hanging.

**Comment by dorbin** [comment]
@tillig 
Did you use Halyard to configure CI? If so, could you provide the specific steps you took?

When you use Halyard to enable CI, for example...

` hal config ci jenkins enable`

...Halyard is supposed to notice that you enabled a CI service and enable Igor for you upon `hal deploy apply`. If that's not working, we'll need to have a look.

I agree though that the linked doc is unhelpful. I'll update it after this issue is resolved. 

Thanks!

**Comment by tillig** [comment]
I was following [the guide I linked](https://www.spinnaker.io/setup/ci/jenkins/) and got all the way down to "Configuring Spinnaker."

Close to the first step, just after "Prerequisites," I did `hal config ci jenkins enable`. While the guide doesn't actually say when to run `hal deploy apply` I've taken to doing that reasonably often to see what changes occur.

I got down to the "Configuring Spinnaker" stage where it said "Enable Igor." I looked in my Kubernetes cluster and did not see any deployment for `spin-igor` out there after the most recent `hal deploy apply`. Many other services, no Igor. There was also no `igor.yml` in my `~/.hal` folder.

The only way I could resolve the situation, that I could tell, was to manually add the `igor.yml` with the contents:

```yaml
enabled: true
skipLifeCycleManagement: true
```

...[as noted in that forum post](https://community.spinnaker.io/t/spinnaker-and-jenkins-debug/314).

I just installed Halyard and Spinnaker last week so I assume I'm running a version recent enough to include the behavior you mentioned. `hal --version` shows `1.5.0-20180713143726`.

**Comment by dorbin** [comment]
It sounds like...

* Because the Jenkins-setup doc does not explicitly say to run `hal deploy apply` you might not have run it before seeing the vague "Enable Igor" instruction.

* You learned on the community forum how to enable Igor manually.

* Therefore, enhancing the instructions on that doc to include `hal deploy apply` after enabling Jenkins, would in theory solve the problem.

Did you ever invoke `hal deploy apply`? If not, it might be useful to undo the manual enabling of igor in the yaml, then redo...
 
`hal config ci jenkins enable`
`hal deploy apply`

And see if that works. 

Easy enough fix in the docs, I just want to make sure that's all there is, first.

Thanks!

And @lwander fyi.

**Comment by tillig** [comment]
I could have sworn I had done a `hal deploy apply` after enabling Jenkins but you could very well be right, that maybe I didn't.

I removed my manual `igor.yml` from `.hal/default/service-settings` and did another `hal deploy apply` and I do see Igor is still up and running. Fixing the doc should cover it.

Thanks for your patience and help!

**Comment by dorbin** [comment]
#925
